name: Datafile Ruby

on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  build:
    name: Compile native gem for ${{ matrix.platform }}
    runs-on: ubuntu-latest

    container:
      image: rbsys/${{ matrix.platform }}:latest

    strategy:
      matrix:
        platform: [x86_64-linux]

    steps:
      - uses: actions/checkout@v2

      - name: Build gem
        id: cross-gem
        shell: bash
        run: |
          unset RAKE_EXTENSION_TASK_NO_NATIVE
          export RUBY_CC_VERSION=3.1.4,3.2.2

          bundle
          bundle exec rake native gem

          echo "gem-path=$(find ./pkg -name '*-${{ matrix.platform }}.gem')" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v2
        with:
          name: cross-gem
          path: ${{ steps.cross-gem.outputs.gem-path }}
